encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("random", views.random, name="random"),
    path("newpage", views.newpage, name="newpage"),
    path("find", views.find, name="find"),
    path("editpage", views.editpage, name="editpage"), 
    path("random", views.random, name="random"),
    path("<str:title>", views.entrypage, name="entrypage"),
      
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from django import forms
from . import util
from django.core.files.storage import default_storage
import re
from random import choice
markdowner = Markdown()

class NewForm(forms.Form):
    form = forms.CharField(label="search")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
def random(request):
    return render(request, "encyclopedia/random.html")

def newpage(request):
    if request.method == "POST" and request.POST['title']!="" and request.POST['content'] != "" : 
        title = request.POST['title']
        content = request.POST['content']
        util.save_entry(title,content)
        return render(request, "encyclopedia/entrypage.html",{        
        'entry': markdowner.convert(content),
        "title": title
    })
    else:
        return render(request, "encyclopedia/newpage.html")
   
def entrypage(request, title):
    data = util.get_entry(title)
    if data == None:
        data = "Request page was not found"
    return render(request, "encyclopedia/entrypage.html",{        
        'entry': markdowner.convert(data),
        "title": title
    })

def find(request):   
    value = util.list_entries()
    list_of_similar = []
    final = []
    if request.method == "POST": 
        string = request.POST['search']
        string = str(string)
        data = util.get_entry(string)
    if data == None:        
        for entry in value:
            string = string.upper()        
            entry = entry.upper() 
            if string in entry:
                list_of_similar.append(entry)                
            else:
                data = "Request page was not found"      
    for item in list_of_similar:
        item = item.capitalize()
        final.append(item)
        #import pdb;pdb.set_trace()             
    if not list_of_similar:
        return render(request, "encyclopedia/entrypage.html",{        
                    'entry': markdowner.convert(data),
                    "title": request.POST['search']
                })
    else:
        return render(request, "encyclopedia/index.html", {
                "entries": final
                })
def editpage(request):
    if request.method == "POST":
        title = request.POST['edititem']
        content = util.get_entry(title) 
        #import pdb;pdb.set_trace()    
    return render(request, "encyclopedia/editpage.html",{
        "title" : title,
        "content" : content
    })
def random(request):
    title = choice(util.list_entries())
    data = util.get_entry(title)
    #import pdb;pdb.set_trace()
    return render(request, "encyclopedia/random.html",{        
        'entry': markdowner.convert(data),
        "title": title
        
    })

encyclopedia/templates/encyclopedia/entrypage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

        {{entry|safe|escape}}   

{% endblock %}

encyclopedia/templates/encyclopedia/find.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
 ENTRO A FIND
        {{form}}   
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href={{entry}}>{{entry}}</a>
        <form action="{% url 'encyclopedia:editpage' %}" method="post" >
            {% csrf_token%}
            <input type="hidden" name="edititem" value={{entry}}>
            <input  type="submit" name="submit" value="Edit">
        </form> 
           
        </li>
           
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:find' %}" method="post" >   
                    {% csrf_token%}             
                    <input class="search" type="text" name="search" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Page</h1>

    <form action="{% url 'encyclopedia:newpage' %}" method="post" >   
        {% csrf_token%} 
        <label for="title">Title:</label>            
        <input class="textarea" type="text" name="title" id="title" placeholder="Type new page's title">
        <br></br> 
        <label>Page's information:</label>
        <br></br>  
        <textarea id="textarea" name="content" placeholder="Describe the page"></textarea> 
        <br></br>  
        <input  type="submit" id="save" value="Save">
        
       
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/random.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

        {{entry|safe|escape}}   

{% endblock %}